#!/usr/bin/env bash
# llamacpp-synth-quant-lowbit: random-weight llama GGUFs (Q1_0, Q2_0, TQ1_0, TQ2_0) for kernel and graph coverage.
# NOT a pretrained model. Generated by tools/llamacpp/synth_workloads.py: edit that, not this file.
# Contract: docs/workload-contract.md. Backends, build and knobs: docs/llamacpp.md, docs/llamacpp-synth.md.
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
. "$here/../../tools/llamacpp/common.sh"
. "$here/../../tools/llamacpp/synth.sh"
lc_setup
lc_synth_prepare
lc_synth_functional llama Q1_0,Q2_0,TQ1_0,TQ2_0 'around has will' "$here/models.sha256"
