#!/usr/bin/env bash
# llamacpp-synth-quant-iquant: random-weight llama GGUFs (IQ3_S, IQ3_M, IQ4_NL, IQ4_XS) for kernel and graph coverage.
# NOT a pretrained model. Generated by tools/llamacpp/synth_workloads.py: edit that, not this file.
# Contract: docs/workload-contract.md. Backends, build and knobs: docs/llamacpp.md, docs/llamacpp-synth.md.
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
. "$here/../../tools/llamacpp/common.sh"
. "$here/../../tools/llamacpp/synth.sh"
lc_setup
lc_synth_prepare
lc_synth_functional llama IQ3_S,IQ3_M,IQ4_NL,IQ4_XS 'another think her' "$here/models.sha256"
