#!/usr/bin/env bash
# llamacpp-synth-quant-moe: random-weight mixtral GGUFs (Q4_0, Q8_0, Q4_K_M, Q6_K, IQ4_XS, MXFP4_MOE) for kernel and graph coverage.
# NOT a pretrained model. Generated by tools/llamacpp/synth_workloads.py: edit that, not this file.
# Contract: docs/workload-contract.md. Backends, build and knobs: docs/llamacpp.md, docs/llamacpp-synth.md.
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
. "$here/../../tools/llamacpp/common.sh"
. "$here/../../tools/llamacpp/synth.sh"
lc_setup
lc_synth_prepare
lc_synth_functional mixtral Q4_0,Q8_0,Q4_K_M,Q6_K,IQ4_XS,MXFP4_MOE 'about father him' "$here/models.sha256"
