#!/usr/bin/env bash
# llamacpp-synth-mixtral: random-weight mixtral GGUFs (F16, Q8_0, Q4_0, Q4_K_M) for kernel and graph coverage.
# NOT a pretrained model. Generated by tools/llamacpp/synth_workloads.py: edit that, not this file.
# Contract: docs/workload-contract.md. Backends, build and knobs: docs/llamacpp.md, docs/llamacpp-synth.md.
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
. "$here/../../tools/llamacpp/common.sh"
. "$here/../../tools/llamacpp/synth.sh"
lc_setup
lc_synth_prepare
lc_synth_functional mixtral F16,Q8_0,Q4_0,Q4_K_M 'the different get' "$here/models.sha256"
