#!/usr/bin/env bash
# llamacpp-synth-quant-legacy: random-weight llama GGUFs (Q4_0, Q4_1, Q5_0, Q5_1, Q8_0) for kernel and graph coverage.
# NOT a pretrained model. Generated by tools/llamacpp/synth_workloads.py: edit that, not this file.
# Contract: docs/workload-contract.md. Backends, build and knobs: docs/llamacpp.md, docs/llamacpp-synth.md.
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
. "$here/../../tools/llamacpp/common.sh"
. "$here/../../tools/llamacpp/synth.sh"
lc_setup
lc_synth_prepare
lc_synth_functional llama Q4_0,Q4_1,Q5_0,Q5_1,Q8_0 'learn heard their' "$here/models.sha256"
