#!/usr/bin/env bash
# llamacpp-synth-quant-iquant-imatrix: random-weight llama GGUFs (IQ1_S, IQ1_M, IQ2_XXS, IQ2_XS, IQ2_S, IQ2_M, IQ3_XXS, IQ3_XS, Q2_K_S) for kernel and graph coverage.
# NOT a pretrained model. Generated by tools/llamacpp/synth_workloads.py: edit that, not this file.
# Contract: docs/workload-contract.md. Backends, build and knobs: docs/llamacpp.md, docs/llamacpp-synth.md.
set -uo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
. "$here/../../tools/llamacpp/common.sh"
. "$here/../../tools/llamacpp/synth.sh"
lc_setup
lc_synth_prepare
lc_synth_functional llama IQ1_S,IQ1_M,IQ2_XXS,IQ2_XS,IQ2_S,IQ2_M,IQ3_XXS,IQ3_XS,Q2_K_S 'good own during' "$here/models.sha256"
